# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Sinner/Saint"
description: > # this means to ignore newlines until "email:"
   "Every saint has a past and every sinner has a future." - Oscar Wilde

email: ryanstraits@gmail.com
#blog logo
logo: "/assets/images/RMS-large-cntr.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Ryan Straits'
author: 'Ryan Straits'
author_image: "/assets/images/RMS-large-cntr.jpg"

paginate:	7
paginate_path: "/page:num"

url: "http://blog.ryanstraits.com" # the base hostname & protocol for your site
baseurl: ""

encoding: utf-8

# social icons and sharing options
social:
  - icon: home
    url: http://www.ryanstraits.com
    desc: Home

  - icon: twitter
    url: https://twitter.com/ryanstraits
    desc: Connect with me on Twitter
    share_url: http://twitter.com/share
    share_title: ?via=ryanstraits&text=
    share_link: "&amp;url="

  - icon: facebook
    url: https://facebook.com/ryanstraits
    desc: Connect with me on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: instagram
    url: https://instagram.com/ryanstraits/
    desc: Connect with me on Instagram

  - icon: tumblr
    url: http://blipsontheradar.tumblr.com/
    desc: Connect with me on Tumblr
    # share_url: https://www.tumblr.com/widgets/share/tool
    # share_title: "&name?="
    # share_link: link?url=

  - icon: medium
    url: https://medium.com/@ryanstraits
    desc: Connect with me on Medium

