# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Sinner/Saint"
description: > # this means to ignore newlines until "email:"
   "Every saint has a past and every sinner has a future" - Oscar Wilde

email: ryanstraits@gmail.com
#blog logo
logo: "/assets/images/RMS-large.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Ryan Straits'
author: 'Ryan Straits'
author_image: "/assets/images/RMS-large.jpg"

paginate:	5

url: "http://blog.ryanstraits.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - title: twitter
    icon: twitter
    url: https://twitter.com/ryanstraits
#   desc: You should follow me on Twitter
#   share_url: http://twitter.com/share
#   share_title: ?text=
#   share_link: "&amp;url="
#
# - icon:	fa-medium
#   url:	https://medium.com/@ryanstraits
#   desc: Other thoughts
#   share_url: 
#   share_title:
#   share_link:
#
#- icon:	sitemap
#   url: https://www.ryanstraits.com
#   desc: ryanstraits.com
#   share_url: 
#   share_title:
#   share_link:
#
#
#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
#
#  - icon:	github
#    url:	https://github.com/ryanstraits
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:
#
#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
