# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Mid States"
description: > # this means to ignore newlines until "email:"
   <i>The art of the in-between</i>

email: ryanstraits@gmail.com
#blog logo
logo: "/assets/images/DSC0931-sq.jpg"
# blog cover
cover: "/assets/images/simon-stankowski-253345.jpg"

name: 'Ryan Straits'
author: 'Ryan Straits'
author_image: "/assets/images/DSC0931-sq.jpg"

# plugins
plugins: ['jekyll-paginate']

paginate:	7
paginate_path: "/page:num"

url: "http://blog.ryanstraits.com" # the base hostname & protocol for your site
baseurl: ""

encoding: utf-8

# social icons and sharing options
social:
  - icon: sitemap
    url: http://www.ryanstraits.com
    desc: ryanstraits.com

  - icon: twitter
    url: https://twitter.com/ryanstraits
    desc: Connect with me on Twitter
    share_url: http://twitter.com/share
    share_title: ?via=ryanstraits&text=
    share_link: "&amp;url="

  - icon: facebook
    url: https://facebook.com/ryanstraits
    desc: Connect with me on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: instagram
    url: https://instagram.com/ryanstraits/
    desc: Connect with me on Instagram

  - icon: medium
    url: https://medium.com/@ryanstraits
    desc: Connect with me on Medium

