# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Ghost States"
description: > # this means to ignore newlines until "email:"
   <i>The art of the in-between</i>

email: ryanstraits@gmail.com
#blog logo
logo: "/assets/images/2017-07-20 square2.jpg"
# blog cover
cover: "/assets/images/monolith-crop-flip.jpg"

name: 'Ryan Straits'
author: 'Ryan Straits'
author_image: "/assets/images/2017-07-20 square2-logo.jpg"

# plugins
plugins: ['jekyll-paginate']

paginate:	7
paginate_path: "/page:num"

url: "http://blog.ryanstraits.com" # the base hostname & protocol for your site
baseurl: ""

encoding: utf-8

# social icons and sharing options
social:
  - icon: home
    url: http://www.ryanstraits.com
    desc: Home

  - icon: twitter
    url: https://twitter.com/ryanstraits
    desc: Connect with me on Twitter
    share_url: http://twitter.com/share
    share_title: ?via=ryanstraits&text=
    share_link: "&amp;url="

  - icon: facebook
    url: https://facebook.com/ryanstraits
    desc: Connect with me on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: instagram
    url: https://instagram.com/ryanstraits/
    desc: Connect with me on Instagram

  - icon: tumblr
    url: http://blipsontheradar.tumblr.com/
    desc: Connect with me on Tumblr
    # share_url: https://www.tumblr.com/widgets/share/tool
    # share_title: "&name?="
    # share_link: link?url=

  - icon: medium
    url: https://medium.com/@ryanstraits
    desc: Connect with me on Medium

