# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Sinner/Saint"
description: > # this means to ignore newlines until "email:"
   "Every saint has a past and every sinner has a future" - Oscar Wilde

email: ryanstraits@gmail.com
#blog logo
logo: "/assets/images/RMS-large.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Ryan Straits'
author: 'Ryan Straits'
author_image: "/assets/images/RMS-large.jpg"

paginate:	7

url: "http://blog.ryanstraits.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - title: twitter
    icon: twitter
    url: https://twitter.com/ryanstraits
    desc: You should follow me on Twitter
    share_url: http://twitter.com/share

  - title: medium
    icon: medium
    url: https://medium.com/ryanstraits
    desc: Sometimes I write here too
   
  - title: home
    icon: home
    url: https://www.ryanstraits.com
    desc: Home

