---
markdown: kramdown
highlighter: rouge
title: Ghost States
description: "<i>The art of the in-between</i>\n"
email: ryanstraits@gmail.com
logo: "/assets/images/DSC0933-sq.jpg"
cover: "/assets/images/casey-horner-505913-edit.jpg"
name: Ryan Straits
author: Ryan Straits
author_image: "/assets/images/DSC0933-sq.jpg"
plugins:
- jekyll-paginate
paginate: 7
paginate_path: "/page:num"
url: http://blog.ryanstraits.com
baseurl: ''
encoding: utf-8
social:
- icon: sitemap
  url: http://www.ryanstraits.com
  desc: ryanstraits.com
- icon: twitter
  url: https://twitter.com/ryanstraits
  desc: Connect with me on Twitter
  share_url: http://twitter.com/share
  share_title: "?via=ryanstraits&text="
  share_link: "&amp;url="
- icon: facebook
  url: https://facebook.com/ryanstraits
  desc: Connect with me on Facebook
  share_url: https://www.facebook.com/sharer.php
  share_title: "?t="
  share_link: "&amp;u="
- icon: instagram
  url: https://instagram.com/ryanstraits/
  desc: Connect with me on Instagram
- icon: microphone
  url: http://www.sixthdegreepod.com
  desc: Check out my podcast
- icon: spotify
  url: https://open.spotify.com/user/ryanstraits/playlist/5cZUMgliJdvmWurhudO2jK?si=l1zBGGn_QhGU3odAKZielA
  desc: I made you a mixtape
timezone: America/Chicago
